version: '3'

services:
  db:
    image: postgres:latest
    container_name: movie_db
    volumes:
      - ./Data/db/:/var/lib/postgresql/data
      - ./Data/initial/:/home/
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=duy
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"

  backend:
    container_name: movie_backend
    build: ./Backend
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=db
      - POSTGRES_USER=duy
      - POSTGRES_PASSWORD=1
    tty: true
    depends_on:
      - db
    restart: always

  frontend:
    container_name: movie_webapp
    build: ./Frontend
    volumes:
      - ./Frontend/movie_webapp:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always