# Generated by Django 4.1.7 on 2023-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='./movie_manager/material/poster/0.jpg', upload_to='./movie_manager/material/poster/'),
        ),
    ]
