# Generated by Django 4.1.7 on 2023-03-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0002_user_rating_movie_remove_movie_genres_alter_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
