# Generated by Django 4.1.7 on 2023-03-27 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.BinaryField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
